language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo
script: hugo -t casper
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.evanbrown.io
  region: us-west-2
  endpoint: www.evanbrown.io.s3-website-us-west-2.amazonaws.com
  local-dir: public
  on:
    repo: evandbrown/evanbrown.io
