baseurl = "http://evanbrown.io"
languageCode = "en-US"
title = "evanbrown.io"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2015"

[params]
  description = "I'm Evan. I write about tech, Seattle, and being a dad."
  cover = "img/cover-nyc.jpg"
  author = "Evan D. Brown"
  authorlocation = "Seattle, WA"
  authorwebsite = "http://evanbrown.io"
  bio= "Dad, developer, Googler in Seattle."
  logo = "img/logo.png"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  githubName = "evandbrown"
  twitterName = "evandbrown"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
